version: '3.9'

networks:
  gateway-network:
    external: true

services:
  thirdparty:
    image: ${REGISTRY_HOST}/${REGISTRY_PUBLISHER}/${PROJECT_NAME}:latest
    networks: 
      - gateway-network
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      NODE_ENV: ${NODE_ENV}
      APPNAME: ${APPNAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_ACCESS_EXPIRE: ${JWT_ACCESS_EXPIRE}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_REFRESH_EXPIRE: ${JWT_REFRESH_EXPIRE}
      MBAPP_HOST: ${MBAPP_HOST}
      MBAPP_APIKEY: ${MBAPP_APIKEY}
      BOOKINGAPP_HOST: ${BOOKINGAPP_HOST}
      BOOKINGAPP_APIKEY: ${BOOKINGAPP_APIKEY}
      API_CHUNK_SIZE: ${API_CHUNK_SIZE}
    volumes:
      - /datadrive/thirdpartyservice/logs:/usr/src/app/logs
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.docker.network=gateway-network
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.${PROJECT_NAME}-http.rule=PathPrefix(`/thirdparty`)
        - traefik.http.routers.${PROJECT_NAME}-http.entrypoints=http
        - traefik.http.routers.${PROJECT_NAME}-http.middlewares=pop-header,pop-stripprefix
        # - traefik.http.routers.${PROJECT_NAME}-http-manage.rule=PathPrefix(`/manage3rd`)
        # - traefik.http.routers.${PROJECT_NAME}-http-manage.entrypoints=http
        # - traefik.http.routers.${PROJECT_NAME}-http-manage.middlewares=pop-header,pop-internal-auth,pop-stripprefix
        # - traefik.http.routers.${PROJECT_NAME}-https.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
        # - traefik.http.routers.${PROJECT_NAME}-https.entrypoints=https
        # - traefik.http.routers.${PROJECT_NAME}-https.tls=true
        # - traefik.http.routers.${PROJECT_NAME}-https.tls.certresolver=le
        - traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=3200